Repository DPGAlliance/dpg-standard, pull requests merged in 2020-10, with the labels that each got.

#12 Add Michael Downey to endorsers
  endorsement.md
Labels: endorsement

#14 DOC: added CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#13 DOC: created governance.md
  README.md
  governance.md
Labels: documentation

#16 MAINT: remove duplicate child safety section
  standard-questions.md
Labels: documentation

#17 MAINT: removed transparency section
  standard-questions.md
Labels: documentation

#11 Clarified wording around CC licenses
  CHANGELOG.md
  standard.md
Labels: minor fix

#3 add "and removing" to 9c re: illegal content
  CHANGELOG.md
  standard.md
Labels: minor fix

#2 Update Language on 7
  CHANGELOG.md
  standard.md
Labels: minor fix

#21 Updated standards question
  standard-questions.md
Labels: documentation

#23 MAINT: update to version 1.0.5
  CHANGELOG.md
  README.md
  governance.md
  standard.md
Labels: documentation

#24 Added my name to the endorsement list
  endorsement.md
Labels: endorsement
